export enum Messages{
    NOT_FOUND = 'Data not found.',
    UPDATE_SUCCESS = 'is updated successfully.',
    ALREADY_REGISTERED = 'is already registered',
    REGISTERED_SUCCESS = 'registered successfully',
    USER_NOT_FOUND = 'User with this email doesn\'t exist.',
    DOES_NOT_MATCH = 'does not match.',
    LOGIN_SUCCESS = 'You are login successfully.',
    OTP_NOT_MATCHED = 'Please enter correct OTP or EMAIL',
    OTP_EXPIRED = 'OTP expired',
    EMAIL_VERIFY = 'Your email is verified',
    EMAIL_SENT = 'Email sent successfully.',
    EMAIL_INCORRECT = 'Email is incorrect',
    EMAIL_FORMAT_NOT = 'Email format not found',
    USER_FOUND = 'User Found Successfully',
    ERROR_UPDATE = 'Error while updating the user',
    FAILED_TO = 'Failed to',
    INCORRECT_PASSWORD = 'Your current password is incorrect.',
    CONFIRM_PASSWORD = 'Your new and confirm password is does not match.',
}